/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import Classes.Excecao;
import Classes.Professor;

import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.Dimension;


public class frmCadastrodeExcecoes extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipalCadastro
     */
    public frmCadastrodeExcecoes() {
    	setSize(new Dimension(500, 500));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    String dia, mes, ano;
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setText("CADASTRO DE EXCE\u00C7\u00D5ES - DIAS LIVRES");

        lblNome.setText("DATA: ");

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        
        JLabel lblDisciplina = new JLabel();
        lblDisciplina.setText("MOTIVO DA EXCE\u00C7\u00C3O");
        
        txtExcecao = new JTextField();
        
        JButton btnVoltar = new JButton();
        btnVoltar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });
        btnVoltar.setText("VOLTAR");
        //final String dia,mes,ano;
        JComboBox cmbDia = new JComboBox();
        cmbDia.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dia = cmbDia.getSelectedItem().toString();
        		System.out.println(dia);
        	}
        });
        cmbDia.setModel(new DefaultComboBoxModel(new String[] {" ","1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"}));
        cmbDia.setToolTipText("1");
        
        cmbMes = new JComboBox();
        cmbMes.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		mes = cmbMes.getSelectedItem().toString();
        		System.out.println(mes);
        	}
        });
        cmbMes.setModel(new DefaultComboBoxModel(new String[] {" ","Janeiro", "Fevereiro", "Mar\u00E7o", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"}));
        
        cmbAno = new JComboBox();
        cmbAno.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ano = cmbAno.getSelectedItem().toString();
        		System.out.println(ano);
        	}
        });
        cmbAno.setModel(new DefaultComboBoxModel(new String[] {" ","2021", "2022"}));
        
        btnCarregarDados = new JButton();
        btnCarregarDados.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Excecao ex = new Excecao();
        		ex.carregarDados();
        		dispose();
        	}
        });
        btnCarregarDados.setText("CARREGAR DADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(224)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnCarregarDados, GroupLayout.PREFERRED_SIZE, 446, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(106)
        					.addComponent(lblTitulo))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblNome)
        					.addGap(33)
        					.addComponent(cmbDia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(cmbMes, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(cmbAno, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(btnVoltar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btnCadastrar, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 446, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblDisciplina, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(txtExcecao, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE)))
        			.addGap(776))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(29)
        			.addComponent(lblTitulo)
        			.addGap(30)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cmbDia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cmbMes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cmbAno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNome))
        			.addGap(26)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtExcecao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblDisciplina))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnCadastrar, GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        			.addGap(43)
        			.addComponent(btnVoltar, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        			.addGap(19)
        			.addComponent(btnCarregarDados, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    	Excecao e = new Excecao();
    	String data = dia +" "+ mes +" "+ ano;
    	e.setData(data);
    	e.setMotivo(txtExcecao.getText());
        System.out.println(e.getData());
        System.out.println(e.getMotivo());
        e.salvaremArquivo();
        dispose();
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    public static void main(String args[]) {
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastrodeExcecoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private JTextField txtExcecao;
    private JComboBox cmbMes;
    private JComboBox cmbAno;
    private JButton btnCarregarDados;
}
