/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import Classes.Excecao;
import Classes.Professor;

import javax.swing.JComboBox;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Vector;
import java.awt.event.ActionEvent;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author FlavioBarros
 */
public class frmReposicao extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipalCadastro
     */
    public frmReposicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        pnResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultado = new javax.swing.JTextArea();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setText("CADASTRO DE REPOSI\u00C7\u00C3O");

        lblNome.setText("PROFESSOR");

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        pnResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("  Resultado  "));

        txtAreaResultado.setColumns(20);
        txtAreaResultado.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultado);

        javax.swing.GroupLayout pnResultadoLayout = new javax.swing.GroupLayout(pnResultado);
        pnResultado.setLayout(pnResultadoLayout);
        pnResultadoLayout.setHorizontalGroup(
            pnResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnResultadoLayout.setVerticalGroup(
            pnResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        
        JLabel lblDisciplina = new JLabel();
        lblDisciplina.setText("DATAS DISPON\u00CDVEIS");
        
        Professor p = new Professor();
        ArrayList<String> professor = p.carregarDados();
        int n = professor.size();
        Vector<String> vProfessor = new Vector<>();
        vProfessor.addAll(professor);
        cmbProfessor = new JComboBox(vProfessor);
        
        cmbProfessor.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        	}
        });
        
        Excecao e = new Excecao();
        ArrayList<String> datas = e.carregarDados();
        int m = datas.size();
        Vector<String> vData = new Vector<>();
        vData.addAll(datas);
        cmbDatas = new JComboBox(vData);
        cmbDatas.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(47)
        					.addComponent(pnResultado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(38)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblDisciplina, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(lblNome)
        									.addGap(82)
        									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        										.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        											.addPreferredGap(ComponentPlacement.RELATED)
        											.addComponent(cmbDatas, 0, 220, Short.MAX_VALUE))
        										.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        											.addPreferredGap(ComponentPlacement.RELATED)
        											.addComponent(cmbProfessor, 0, 329, Short.MAX_VALUE)))
        									.addGap(29))
        								.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        									.addComponent(lblTitulo)
        									.addGap(153)))
        							.addComponent(btnSair)))))
        			.addGap(44))
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGap(126)
        			.addComponent(btnCadastrar)
        			.addPreferredGap(ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
        			.addComponent(btnLimpar)
        			.addGap(143))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(54)
        					.addComponent(btnSair)
        					.addGap(30))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(lblTitulo)
        					.addGap(44)))
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblNome)
        						.addComponent(cmbProfessor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(38)
        					.addComponent(lblDisciplina))
        				.addComponent(cmbDatas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(71)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnLimpar)
        				.addComponent(btnCadastrar))
        			.addGap(81)
        			.addComponent(pnResultado, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        btnCadastrar.setEnabled(false);
        btnLimpar.setEnabled(true);
        txtAreaResultado.append("O professor(a): "+cmbProfessor.getSelectedItem().toString()+"\n");
        txtAreaResultado.append("Cadastrou a sua reposição para o dia : "+cmbDatas.getSelectedItem().toString()+"\n");
        txtAreaResultado.setEditable(false);        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
  
        btnCadastrar.setEnabled(true);
        btnLimpar.setEnabled(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSair().setVisible(true);
            }
        });
        
        this.dispose();
        
        
    }//GEN-LAST:event_btnSairActionPerformed

    public static void main(String args[]) {
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReposicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnResultado;
    private javax.swing.JTextArea txtAreaResultado;
    private JComboBox cmbProfessor;
    private JComboBox cmbDatas;
}
